# Generated by Django 5.0.6 on 2024-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_book_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='arriving_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
