# Generated by Django 5.0.6 on 2024-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_arriving_date_alter_book_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='user',
        ),
        migrations.AddField(
            model_name='usergenre',
            name='no_time_genere_read',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
