# Generated by Django 5.0.6 on 2024-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bookissue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
